### ISSUE TITLE
Lilu.kext errors

### ISSUE THREAD

**Issue by Piker-Alpha** [vit9696/Lilu#10]
I am trying out v1.4 of Lilu.kext for the first time, and run into load issues. Here is the output of:
```
sudo kextutil Lilu.kext
```

```
Diagnostics for Lilu.kext:
Code Signing Failure: not code signed
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "Lilu.kext"
kext signature failure override allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/Volumes/M2/Extra/Extensions/Lilu.kext"
(kernel) Kext as.vit9696.Lilu start failed (result 0x5).
(kernel) Kext as.vit9696.Lilu failed to load (0xdc008017).
(kernel) Failed to load kext as.vit9696.Lilu (error 0xdc008017).
Failed to load Lilu.kext - (libkern/kext) kext (kmod) start/stop routine failed.
```
I use the following extra boot arguments:
```
-lilubeta -igfxbeta
```
This is with macOS Hight Sierra 10.13 What should/can I do to resolve this?

**Note**: This is with RevoBoot. Not Clover. Just in case it matters.

**Comment by vit9696** [comment]
Hi, it does not really matter which loader to use, so RevoBoot should be fine. What does matter though is the loading time, I hook certain apple policies that only start in the beginning of the boot process. So you must load Lilu as early as possible.
There is a handy workaround if you cannot easily control the order — https://github.com/PMheart/LiluFriend.
If it still fails… mhm, try -liludbg and check the kernel log, maybe it has something valuable?

**Comment by Piker-Alpha** [comment]
Hi,

Thanks, but kext injection works fine in RevoBoot, and thus LiluFriend.kext won't help me.

I knew that it had to be something else and I figured it out. I looked at the source code and it turns out that boot argument **-s** disables the kext.

Would you mind adding it to the documentation so that nobody else have to deal with this anymore? Thanks!

p.s. I don't quite understand the need of **-lilubeta** IMHO it would be better to enable the kext by default and use something like -lilubetaoff to disable it.

**Comment by vit9696** [comment]
Oh, right, -s and -x indeed disable Lilu, it is done for safety reasons for real macs, where you cannot easily edit the boot-args. Wahat I heard is that some people inject FakeSMC and friends from single mode, and then boot to normal OS, so I actually might add some argument to force-enable Lilu for this case…

As for -lilubeta and stuff, I don't install beta OS updates, so I usually don't know whether it works or not. Last time when 10.12 appeared, kernel patcher panic'ed heavily, so I added these safety arguments.

One could always edit the source for his own needs or wait for an official OS release. I think I will enable HighSierra support when it gets more stable, closer to the end of August or September :)
