### ISSUE TITLE
High Sierra macOS installer support

### ISSUE THREAD

**Issue by Piker-Alpha** [vit9696/Lilu#11]
Please add:
```
installOrRecovery |= PE_parse_boot_argn("auth-root-dmg", tmp, sizeof(tmp));
```
@ https://github.com/vit9696/Lilu/blob/master/Lilu/Sources/kern_start.cpp#L116

**Comment by vit9696** [comment]
Hi, thank you :) Added here: https://github.com/vit9696/Lilu/commit/a7e38fa650de1ca083c3ddb4bdb940ac676a3f7e
