### ISSUE TITLE
Missing built instructions for plugins

### ISSUE THREAD

**Issue by Piker-Alpha** [vit9696/Lilu#12]
I was asked to look into this but I do not have the time for it while on holidays so here goes:

Please add some useful built instructions for plugins.

**Comment by vit9696** [comment]
Well, I hardly have time to write instructions either, and the one I have I would better spend on more useful stuff. I would gladly accept a pull request with a decent FAQ though.

**Comment by Piker-Alpha** [comment]
I hear you. Let's try to make it easier. First. The problem appears to be related, specifically, to missing file errors where plugins use:

SDK/Headers
SDK/Library

Which SDK is that? I assume one for Lilu.kext since Xcode uses SDKs

**Comment by vit9696** [comment]
Well, usually the plugins have a note that copying a debug version of `Lilu.kext` into the build dir is required… Mostly it is enough.

**Comment by Piker-Alpha** [comment]
Understood. Thanks.
