### ISSUE TITLE
High Sierra Public Beta 4, Lilu triggered rebuild prelinkedkernel 

### ISSUE THREAD

**Issue by tjxddt** [vit9696/Lilu#17]
![img_20170811_121228_259](https://user-images.githubusercontent.com/14345269/29221905-7a609120-7e8e-11e7-8092-34de9d4c9dcb.jpg)

**Comment by vit9696** [comment]
Are you sure that's Lilu behind it? As far as I am aware this very rarely happens but it is unrelated to Lilu, but rather a boot.efi/kext injection bug.
