### ISSUE TITLE
-s disables Lilu and its plugins

### ISSUE THREAD

**Issue by Krazubu** [vit9696/Lilu#19]
Hi, I know this is intentional but this is not the purpose of -s mode and is in fact impractical. Disabling would better be made by safe mode (or kernel parameter).
For instance if I boot to single user mode for some OS debugging purpose and manual kext loading, I can't "hot load" the OS and see my changes as the system will fail because of missing Lilu, Whatevergreen etc…

**Comment by vit9696** [comment]
Hi,
I very well understand your pain, and for that reason I added `-liluforce` boot argument, that effectively enables Lilu and its plugins regardless of the boot mode.
Please tell me if it works fine for you.

**Comment by Krazubu** [comment]
Ok, but it's more a question of design, this should not be a default behavior. -s mode is not supposed to disable stuff and this makes Lilu a special case among all the kexts.
Why not simply use -liluoff if we do want to disable it, instead of "disable the disabling" with -liluforce ?

**Comment by vit9696** [comment]
Mainly because of native hardware Lilu is designed to work with. It may not be easy to get to boot arguments in this case, whereas cmd+s is always near.

**Comment by Krazubu** [comment]
I get your point.
