### ISSUE TITLE
Graphics Acceleration Glitch sometime after sleep, Double click to wake screen up

### ISSUE THREAD

**Issue by whatsnewsisyphus** [vit9696/Lilu#2]
Hello, Thanks for the all the work. While the fix worked to get rid of the initial black screen, it looks like I am having some post sleep issue. If I touch anyhting, the computer wakes up, fans spinning and all, but the display needs another click to wake up. Not a big deal, but maybe an indicator of something?
The bigger problem is that after shortly after waking up, if I use anything HW accelerated like Firefox (and perhaps the system itself) it goes into super laggy / glitchy / flashy mode where even moving a finder window is slow motion blinks across the screen, typing goes one or two letters a second, etc.
Attached below is the ioreg
[ioreg.zip](https://github.com/vit9696/Lilu/files/966226/ioreg.zip)

**Comment by vit9696** [comment]
This has nothing to do with Lilu, since Lilu does not do anything by itself.
