### ISSUE TITLE
10.13.2 beta 1 KP

### ISSUE THREAD

**Issue by Gamedev1909** [vit9696/Lilu#28]
We are getting a KP when using 10.13.2 with lilu http://www.insanelymac.com/forum/topic/329143-pre-release-macos-high-sierra-10132/

**Comment by vit9696** [comment]
While I am aware of it, until you create an issue properly and provide the logs/dumps/etc. nothing will be done. Btw, Lilu is opensource and I do not use 10.13 ;P

**Comment by arsradu** [comment]
Hi man,

Could you, please, tell me, what kind of logs do you need? :) I'm trying to provide them as soon as possible.

**Comment by ricoc90** [comment]
The KP: https://imgur.com/a/KPIfa

**Comment by vit9696** [comment]
Apple changed (broke) some kernel mapping stuff in 10.13.2. As a result not only Lilu, but VMware, and probably Parallels also stopped loading macOS guest. I have already received some necessary information, and it comes out that the issue will require my direct involvement (or some other dev of course), and the initial fix I added does not fix anything :).

Hopefully I will get some free time before 10.13.2 release to fix it.

**Comment by vit9696** [comment]
Fortunately it was not as bad as I initially thought, and VMware was just broken due to a forgotten param in the config. Fixed as of https://github.com/vit9696/Lilu/commit/cfd40325352e9d1279a1f441a0dab1554694fdf9. You will have to compile it yourself.
