### ISSUE TITLE
On macOS 10.13.1 lilu.kext + intelgraphicsfixup.kext only works with boot flag -liluforce

### ISSUE THREAD

**Issue by najeebanwer** [vit9696/Lilu#32]
My setup is as follows:
Dell XPS 8910
CPU: Intel Core i7-6700, Intel HD 530 Graphics
GPU: NVIDIA GeForce GTX 750 Ti 2GB
RAM: 16GB
SMBIOS model: 17,1
Clover Version: r4318
lilu.kext (1.2.1 release)
intelgraphicsfixup.kext (1.2.0 release)
nvidiagraphicsfixup.kext (1.2.1 release)
All kexts are injected with Clover.

I have been successfully using lilu.kext with intelgraphicsfixup.kext and nvidiagraphicsfixup.kext on macOS 10.12.x and 10.13.0. After upgrading to 10.13.1, I could boot while connected to the NVIDIA GPU but not when connected to the IGPU.

I was already using the boot flag -lilubetaall, so lilu.kext should have been loading even on an unsupported macOS version. However, after some testing I have found that the system will boot when connected to the IGPU only if I add the boot flag -liluforce.

**Comment by vit9696** [comment]
Lilu disables itself based on the boot arguments, so something should be present in your nvram or clover config. Check Lilu manuals for a complete list.

**Comment by najeebanwer** [comment]
Thanks. Where would I find the Lilu manuals?
