### ISSUE TITLE
Lilu kext not loaded in High Sierra when applying IntelCapriFramebuffer kext patch

### ISSUE THREAD

**Issue by dreadkopp** [vit9696/Lilu#33]
Hi.

I stumbled upon the following problem:

To get my HD4000 graphics to work correctly i use a clover on-the-fly kext patch in AppleIntelCapriFramebuffer to add LVDS output for internal screen.

As soon as i use this kextpatch Lilu (and thus AppleALC) are not loaded anymore.

i tried -liluforce -lilubeta bootflags but no change in behavior.

Please let me know how can i give you any more info to fix this problem.

Cheers

**Comment by vit9696** [comment]
It could be that clover breaks kextcache, please try the latest Lilu from master.

**Comment by dreadkopp** [comment]
using 1.2.1 currently but downloading xcode right now for latest version from git

**Comment by dreadkopp** [comment]
for some weird reason the clover version i was using effed it up. updated from 4259 to 4330 and sound came alive :)

**Comment by vit9696** [comment]
Huh, not impossible there was not a bug in clover, still very surprising. Thanks for the research.
