### ISSUE TITLE
Clarify installation process

### ISSUE THREAD

**Issue by marnovo** [vit9696/Lilu#34]
The readme mentions:

> You should install this kext along with the plugin kexts depending on it.

What does "installing" a kernel extension entails? A more detailed process would be beneficial to people less familiar with the processes and lingo: any additional steps or processes involved (and if so, it would be nice to explain inline or link to somewhere that explains it). Thanks!

**Comment by 07151129** [comment]
See https://developer.apple.com/library/content/documentation/Darwin/Conceptual/KernelProgramming/Extend/Extend.html#//apple_ref/doc/uid/TP30000905-CH220-BEBEGICJ and https://clover-wiki.zetam.org/Configuration/SystemParameters#InjectKexts
