### ISSUE TITLE
Lilu Decompress Error

### ISSUE THREAD

**Issue by loganmelott211** [vit9696/Lilu#36]
In -v Lilu Gives Me A Decompress Error Not Sure If Its With The Kext Or Not
![fullsizerender](https://user-images.githubusercontent.com/29647778/36636419-d062117e-1994-11e8-9b5b-b5ef8cd12ea3.jpg)

**Comment by loganmelott211** [comment]
Here is what it says if you can't see it 
Lilu:    mach @ decompression disallowed due to low out size 3843

**Comment by vit9696** [comment]
Hi, it literally says that your compressed image after decompression is 3843 bytes long, which obviously is very small. I think your prelinkedkernel is corrupted and you need to rebuild it via `kextcache` utility (google for it).
