### ISSUE TITLE
Could you please add this new plugin to the known plugin list?

### ISSUE THREAD

**Issue by Austere-J** [vit9696/Lilu#4]
Hi! I made a new plugin to unlock the Night Shift feature for all Macs. 
Could you please add this plugin to the list?

Source Code: https://github.com/Austere-J/NightShiftUnlocker

Thanks. :)

**Comment by vit9696** [comment]
Hi, actually I noticed your plugin a bit earlier, and had some questions:
* Does it actually work from clover extensions? I don't see why it should not, but there was a strange issue in Chinese I could not fully comprehend.
* Patching _CBU_IsNightShiftSupported is not enough for some use cases, you need to ensure that your display is not detected as a TV or a projector. This is a common issue for multimonitor configurations. As far as I am aware it is determined by screen EDID, which need to be [modified](https://apple.stackexchange.com/a/278790). Could you check all the configurations and add some instruction on how to correct screen EDID (as far as I know Clover had something as well)?
* Byte patching is a very bad idea when you need to change the public function. Yesterday I added a change allowing you to use MachInfo with its symbol address solver in userspace, could you rewrite your code to be more compatible with future macOS versions (at least the minor updates)? I could share some sample code if you drop e-mail me with this nickname at avp.su.

**Comment by Austere-J** [comment]
Hi, thanks for your reply.

> Does it actually work from clover extensions? I don't see why it should not, but there was a strange issue in Chinese I could not fully comprehend.

No. Let me briefly explain that issue in Chinese for you.  
Someone reported that he was unable to use Clover's kext injector to load NightShiftUnlocker (NSU). `kextstat` reported that NSU was loaded, but I didn't find any logs releated to NSU in his kernel log.   
So I tried by myself, and in my case, NSU could not be injected by Clover. `kextstat` reported that NSU was not loaded.  

> Patching _CBU_IsNightShiftSupported is not enough for some use cases, you need to ensure that your display is not detected as a TV or a projector. 

Yes, I agree with that. Someone on insanelymac reported that he was unable to use NSU with his external TV. Although Apple indicates that Night Shift does not apply to connected TVs and projectors, it is not a rare issue that some monitors cannot be recognized correctly by macOS. 

> This is a common issue for multimonitor configurations. As far as I am aware it is determined by screen EDID, which need to be modified. Could you check all the configurations and add some instruction on how to correct screen EDID (as far as I know Clover had something as well)?

It's hard for me to check all configurations because all my monitors and their EDIDs can be detected correctly, but I will try to collect some data and add an instruction. :)

> Byte patching is a very bad idea when you need to change the public function. Yesterday I added a change allowing you to use MachInfo with its symbol address solver in userspace, could you rewrite your code to be more compatible with future macOS versions

Yes, hard coding everything is indeed bad. Good, I will look at it and come up with a new solution. I already sent an email to you. Looking forward to your reply.

**Comment by vit9696** [comment]
> No. Let me briefly explain that issue in Chinese for you.
Someone reported that he was unable to use Clover's kext injector to load NightShiftUnlocker (NSU). kextstat reported that NSU was loaded, but I didn't find any logs releated to NSU in his kernel log. So I tried by myself, and in my case, NSU could not be injected by Clover. kextstat reported that NSU was not loaded.

That makes little sense, to be honest. But I think your OSBundleLibraries could be the cause. Clover injects the kexts very early, and it is very likely that it makes a conflict. Please try the ones from Shiki or any other plugin, it should work.

> It's hard for me to check all configurations because all my monitors and their EDIDs can be detected correctly, but I will try to collect some data and add an instruction. :)

Thanks :)

> Yes, hard coding everything is indeed bad. Good, I will look at it and come up with a new solution. I already sent an email to you. Looking forward to your reply.

Got none unfortunately, are you sure you did not make a typo?

**Comment by Austere-J** [comment]
> But I think your OSBundleLibraries could be the cause.
Thanks for your suggestion. I will try that.

> Got none unfortunately, are you sure you did not make a typo?
That's weird. I clicked the email address on that website and sent the email.  
Anyway, could you please send the sample code to `austere.j@gmail.com`?

**Comment by Austere-J** [comment]
Good, I got your email. Thanks :)

**Comment by vit9696** [comment]
That's right, I added your plugin to the list, let's continue our further discussion in private then.
