### ISSUE TITLE
What does Lilu mean?

### ISSUE THREAD

**Issue by allenwq** [vit9696/Lilu#42]
Thanks for the awesome library! 

But Just curious, what does the word "Lilu" mean?

**Comment by vit9696** [comment]
Enjoy :) Wikipedia gives some basic idea for the meaning, which is a [masculine form of Lilith](https://en.wikipedia.org/wiki/Lilu_(mythology)).

**Comment by allenwq** [comment]
So it's actually means a dangerous demon of the night? :-)
