### ISSUE TITLE
New Plugin: PatchCom4360

### ISSUE THREAD

**Issue by coderobe** [vit9696/Lilu#6]
Adds a required patch for several broadcom cards that work with apples 4360 kext

link: https://github.com/coderobe/PatchCom4360

**Comment by coderobe** [comment]
For unknown reasons, this plugin is unstable, likely because of kext loading / lilu injection race conditions - closing this for now until i've got more info and/or a fix

**Comment by vit9696** [comment]
The only thing I could think of is non-bootloader loading. It is explicitly stated that it is a bad idea to load Lilu and its plugins from /L/E or /S/L/E, they will randomly fail unless you use apple id & security module flag. Be sure not to do that.

**Comment by coderobe** [comment]
i am using clover kext injection for lilu and this plugin, but even that appears to be unreliable.
This is the first plugin this kind of issue occurs with though
